### ISSUE TITLE
New container pip downgrades transformers to 4.18

### ISSUE THREAD

**Issue by nmb-paperspace** [zzweig/huggingface-graphcore#9]
New container is frozen to pip 21.3 and so transformers gets installed at 4.18 and not 4.20

**Comment by nmb-paperspace** [comment]
This happens in both `introduction_to_optimum_graphcore.ipynb` and `text_classification.ipynb`.

**Comment by nmb-paperspace** [comment]
Notebook startup command `PIP_DISABLE_PIP_VERSION_CHECK=1` to `PIP_DISABLE_PIP_VERSION_CHECK=0` might allow latest pip again - try this.

**Comment by nmb-paperspace** [comment]
Doesn't work

**Comment by denizb-graphcore** [comment]
The issue is the wrong ubuntu version of the image. It should be changed to ubuntu 20.

**Comment by nmb-paperspace** [comment]
OK thanks. It was Ubuntu 20.04 before and got changed to 18.04 Aug 4th. Changing it back to 20.04 resolves this issue.
